### ISSUE TITLE
Remove padding at the bottom

### ISSUE THREAD

**Issue by jespalmer** [Jwsonic/wedding-site#2]
RSVP section should have no bottom padding or have a footer that matches the nav bar and says JESYKA + JOHN in the center aligned.

**Comment by jespalmer** [comment]
I just checked and it doesn't seem updated?

**Comment by Jwsonic** [comment]
Maybe it's because I haven't uploaded it yet.... :D :+1:

**Comment by jespalmer** [comment]
FINEEEE lol
